### ISSUE TITLE
Raster function differences between Desktop and Pro

### ISSUE THREAD

**Issue by abrowning80** [Esri/solutions-raster-functions#4]
Differences between results obtained in desktop and Pro when running the same raster functions on the same data in the 2 programs.  

Data is in NetCDF format and has been imported into a mosaic dataset within a file geodatabase.

Have looked at the pixel values at the same locations in each and it appears that what ever raster function is run within pro the same values are returned.  This potentially point towards that the definition query that is being run at the beginning of the raster function to extract the relevant variable (eg rh2m) is not running successfully in Pro.

**Comment by csmoore** [comment]
Looks like this can be closed
